"""Keeps the cross-backend parity fixture honest.

``tests/fixtures/phmm_parity.npz`` is what the PyTorch backend is checked
against, but it is a committed file: nothing stops the TensorFlow backend from
moving on and leaving it behind, which would turn the torch parity tests into a
check against a stale snapshot.

This test re-derives the fixture here and compares. If it fails, the two
backends have genuinely diverged -- either the TF change was intended, in which
case regenerate the fixture and re-run the torch suite, or it was not.
"""

import numpy as np
import pytest

from tests.fixtures.generate_parity_fixtures import FIXTURE, collect

#: The fixture is regenerated by the same code path, so anything beyond
#: run-to-run nondeterminism is a real divergence.
RTOL = 1e-6
ATOL = 1e-6


@pytest.fixture(scope="module")
def regenerated():
    return collect()


def test_fixture_exists() -> None:
    assert FIXTURE.exists(), (
        f"{FIXTURE} is missing. Generate it with "
        "'python tests/fixtures/generate_parity_fixtures.py'."
    )


def test_fixture_has_the_same_keys(regenerated) -> None:
    with np.load(FIXTURE) as stored:
        stored_keys = set(stored.files)
    assert set(regenerated) == stored_keys, (
        "the parity fixture records a different set of arrays than the "
        "generator now produces; regenerate it."
    )


def test_fixture_values_are_current(regenerated) -> None:
    with np.load(FIXTURE) as archive:
        stored = {key: archive[key] for key in archive.files}
    for key in sorted(set(regenerated) & set(stored)):
        np.testing.assert_allclose(
            regenerated[key], stored[key], rtol=RTOL, atol=ATOL,
            err_msg=(
                f"{key} no longer matches the committed fixture. If the "
                "TensorFlow backend changed on purpose, regenerate the "
                "fixture and re-run the torch parity tests."
            ),
        )
